# Requires
#   coffee-script (npm install coffee-script) <- will fail silently without it
#   uglifyjs      (installed and in PATH)
#   stitch        (npm install stitch)
#   ncp           (npm install ncp)
fs = require 'fs'
stitch  = require('stitch');
require('coffee-script/register');

{spawn} = require 'child_process'
{ncp} = require 'ncp'

target_dir = '../js/'
deploy_dir = 'deploy/'
build_dir = 'build/'
src_dir = __dirname + '/src'

target_file_name = 'aligulac'


create_package = (callback) ->
    if not fs.existsSync deploy_dir
        fs.mkdirSync deploy_dir

    console.log "Source directory: #{src_dir}"
    pckage = stitch.createPackage({
      paths: [src_dir]
    })

    pckage.compile (err, source) ->
        if err
            console.error "Stitch error: #{err}"
            process.exitCode = 1
            callback(err) if callback
            return
        fs.writeFile("#{deploy_dir}#{target_file_name}.js", source, (err) ->
            if err
                console.error "Write error: #{err}"
                process.exitCode = 1
                callback(err) if callback
                return
            console.log "Compiled #{target_file_name}.js package"
            callback() if callback
        )

js_file_regex = ///.*\.js$///
get_files = (dir, callback) ->
    fs.readdir dir, (err, files) ->
        callback (dir + file for file in files when file.match(js_file_regex)?)

log = (msg) ->
    console.log msg

build = (callback) ->
    log "Building..."
    create_package (err) ->
        if err
            console.error "Build failed"
            process.exitCode = 1
        callback(err) if callback

deploy = () ->
    build (err) ->
        if err
            console.error "Deploy stopped due to build error"
            process.exit(1)
            return

        log "Deploying..."
        if not fs.existsSync deploy_dir
            fs.mkdirSync deploy_dir

        f = deploy_dir + target_file_name
        uglify = spawn 'uglifyjs', ['-m', '-c', '-o', f + '.min.js', f + '.js']
        uglify.stderr.on 'data', (data) ->
            process.stderr.write data.toString()
        uglify.on 'exit', (code) ->
            if code is 0
                log "Uglyify done."
                copy()
            else
                log "Uglyify failed with code #{code}"
                process.exit(1)


copy = () ->
    log "Copying..."
    ncp deploy_dir, target_dir, (err) ->
        if err?
            log err
        else
            log "Done!"

task 'build', 'build all coffee files', (options) ->
    build (err) ->
        if err
            process.exit(1)

task 'copy', 'copies files from deploy to target', (options) ->
    copy()

task 'deploy', 'build and combine all coffee files', (options) ->
    deploy()

task 'clean', 'remove all compiled files', (options) ->
    rm = spawn 'rm', ['-r', deploy_dir, build_dir]
