name: Build and Publish Docker Image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable-docker-publish.yml
    with:
      tags: |
        type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
        type=sha,format=short
    secrets:
      S3_STATIC_ACCESS_KEY: ${{ secrets.S3_STATIC_ACCESS_KEY }}
      S3_STATIC_SECRET_KEY: ${{ secrets.S3_STATIC_SECRET_KEY }}
